### ISSUE TITLE
Problem in the form!

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#101]
Looks like there's a problem with the display of the list of languages!

![image](https://user-images.githubusercontent.com/33317799/175167080-e45e75fa-fbee-40d7-8758-348280b1e8ef.png)

**Comment by PonteIneptique** [comment]
I removed the CSs...
Corrected 😁

Le jeu. 23 juin 2022 à 12:48 AM, Alix Chagué ***@***.***> a
écrit :

**Comment by alix-tz** [comment]
Thank you!
