### ISSUE TITLE
Add link to Catalog file on Zenodo

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#110]
in home.html, when clicking on "Download the catalog"

**Comment by alix-tz** [comment]
Hello, currently it opens the raw version of the htr-united.yml file in the htr-united repo. Since that file is synched with Zenodo and published there, it would be more logical to point to the Zenodo repo

**Comment by alix-tz** [comment]
Here is the link to the Zenodo repo: https://doi.org/10.5281/zenodo.6073663

**Comment by alix-tz** [comment]
But actually, @PonteIneptique, it's only the zipped archive of the whole repo that's downloadable. Do you think we could add the htr-united.yml file as a separate downloadable, outside of the zip?

**Comment by PonteIneptique** [comment]
I think it's good that the whole repo is downloadable to be honnest :D

**Comment by alix-tz** [comment]
fixed with #117!
