### ISSUE TITLE
Ajouter un champs de métadonnees type de données

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united.github.io#13]
Avec 5 possibilités:

- `Manuscript`
- `Typed`
- `Mainly manuscript`
- `Mainly typed`
- `Evenly typed and manuscript`

Peut-etre au niveau metric ?

**Comment by alix-tz** [comment]
Je pense qu'on peut créer un champ "script-type" à part entière, il me semble que ça va dans le même sens que le champ "script". A voir si la traduction fr de "typed" peut être un peu plus élégante... une suggestion ?

**Comment by PonteIneptique** [comment]
Pour l'instant cela ira ;)
