### ISSUE TITLE
Simplify bilinguism..

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#22]
As @PonteIneptique suggested, we could implement [Vanilla-i18n](https://github.com/thealphadollar/vanilla-i18n) to make managing the bilingual aspect more easily.

**Comment by alix-tz** [comment]
@PonteIneptique I have a problem making i18n work with the form page.

Because it has been impossible to make vanilla-i18n work locally, I created a dev page to be able to see the results, you can check it at https://htr-united.github.io/dev_document-your-data.html.

The "Language" and "Scripts" fields don't appear correctly. Note that it is not surprising, because they interact with other JS scripts.

What it looks like:
![image](https://user-images.githubusercontent.com/33317799/152691956-155fe87a-a4d8-42cf-b35e-f9a0a7849d39.png)


What it should look like: 
![image](https://user-images.githubusercontent.com/33317799/152691984-ad1dc36e-3902-46b8-923b-00469b6544bb.png)


I have the following errors in the console:

![image](https://user-images.githubusercontent.com/33317799/152691898-4ce2d9f9-9505-475e-9e49-dec5a262d98f.png)

Can you give me a hand?

**Comment by PonteIneptique** [comment]
I'll have a look tomorrow :)

Le dim. 6 févr. 2022 à 6:03 PM, Alix Chagué ***@***.***> a
écrit :

**Comment by PonteIneptique** [comment]
Simple problème d'overlap de variables ;)

https://github.com/HTR-United/htr-united.github.io/commit/41d3719c7f794e88643d107cb0332a92e745c2d3#diff-77e8c519530c1412b59eb877b1e391c898b299c41021a13e3be320a50e440471

Pour fonctionner localement, le truc utilise des requêtes http: utilise `python3 -m http.server` dans le dossier, et relance la commande quand tu changes un truc. Tu auras accès aux requêtes http et tu pourras bosser localement :D

**Comment by alix-tz** [comment]
> Simple problème d'overlap de variables ;)

Ça paraît si bête 🥲 


> Pour fonctionner localement, le truc utilise des requêtes http: utilise `python3 -m http.server` dans le dossier, et relance la commande quand tu changes un truc. Tu auras accès aux requêtes http et tu pourras bosser localement :D

Will do! Désolée pour les push insalubres! :D

**Comment by PonteIneptique** [comment]
J'ai pas push de fichier renommé hein ;)

**Comment by alix-tz** [comment]
🎊
