### ISSUE TITLE
Catalog file generator makes erroneous YAML file if quotes are in the text fields and textarea have newlines

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united.github.io#25]
See https://riptutorial.com/yaml/example/25838/escaping-characters for quotes
See `>` for multiline

**Comment by alix-tz** [comment]
I also noticed that the "project name" field often has an extra closing quote

**Comment by PonteIneptique** [comment]
Use https://github.com/jeremyfa/yaml.js/tree/develop/dist
