### ISSUE TITLE
Ajouter la page avec le catalogue

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united.github.io#38]
Salut Alix, 
Je pensais ajouter une page catalogue avec des petits filtres et une option visualisation type cards, à la https://huggingface.co/models / 
Tu peux te charger du design ? Genre avec https://getbootstrap.com/docs/5.1/components/card/#titles-text-and-links ?
Je m'occupe du JS + JSON
Et je finis sans tarder la partie I18N dès que le petit sieste.

**Comment by alix-tz** [comment]
Finalement tu as fait le plus gros du design ! 💪

**Comment by PonteIneptique** [comment]
Je pensais kickstarter le truc pour que tu ajoutes les infos plus cools :D

**Comment by PonteIneptique** [comment]
Done with #46

**Comment by alix-tz** [comment]
On est plutôt bon sur cette issue, je ferme ! Bravoe encore !
