### ISSUE TITLE
Ajouter éléments How to cite

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#5]
Ex : 

```
<p>
<button class="btn btn-info btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
Mentions légales
</button>
</p>
<div class="collapse" id="collapseExample">
<div class="card card-body">blabla</em>
</div>
</div>
```

**Comment by PonteIneptique** [comment]
> Question primordiale : citer HTR-United a-t-il un sens ?
Vu que des gens l'on déjà fait, oui :) On peut renvoyer vers le fichier CITATION.CFF ou copier les valeurs du CITATION.CFF dans le README / HTML

**Comment by alix-tz** [comment]
A résoudre en ajoutant un lien vers le fichier CITATION.CFF de htr-united/htr-united
