### ISSUE TITLE
Logo des logiciels

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united.github.io#55]
Je me demande si on peut prendre une belle thématique, du genre les logos réutilisent tous un systême type pièce de puzzle ou interconnexions:

![image](https://user-images.githubusercontent.com/1929830/153747652-ea480150-dd54-421e-9850-352b14b80dd5.png)

Avec peut-être un truc à la carte mère:
![image](https://user-images.githubusercontent.com/1929830/153747681-19cdb343-6ad5-430a-9cf3-ab4d4da53e97.png)

Une police commune, et un "logo" simple supplémentaire:

- Aile ou colonne (gallo-)romaine pour HTRVX
- Muffin / Cookie pour Choco Mufin
- HUMGenerator un petit logo de livre / catalogue / bdd
- HTRUC flèche vers le haut (Car c'est le nord ? :D )

![image](https://user-images.githubusercontent.com/1929830/153747742-c5e14e2f-27dc-49fc-a14d-6154599ebd49.png)

**Comment by PonteIneptique** [comment]
Tes logos me vont totalement, mais si tu veux reprendre pour avoir une identité commune / une déclinaison facile, tu peux ! Tu fais comme tu veux, je suis pas le graphiste :D

**Comment by alix-tz** [comment]
Je fais une petite checklist pour la v1 des logos

- [x] HTRVX
- [ ] Choco Mufin
- [x] HUMGenerator
- [x] HTRUC

**Comment by PonteIneptique** [comment]
Woohooo :D 
Thank you so much :)
