### ISSUE TITLE
Have a form to generate Github Actions YAML

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united.github.io#62]
Use some form of optionalization such as `Do you want to generate character badges ?`, `If so, for which kind of data ?`

**Comment by PonteIneptique** [comment]
I started something, I'd be happy to have some feedback on it: https://ponteineptique.github.io/htr-united.github.io/actions.html

**Comment by alix-tz** [comment]
oups...

**Comment by alix-tz** [comment]
If people do like I did (aka copy paste the URL from the next tab where the repo is open), you might want to consider testing the value here 😅

**Comment by PonteIneptique** [comment]
Check https://htr-united.github.io/actions.html ;)

**Comment by PonteIneptique** [comment]
I added a regexp to catch this kind of errors. Feel free to add the link to the actions pages in the Header :D

**Comment by alix-tz** [comment]
J'ai fait une minimini correction sur ta regex, pense à pull si tu veux retravailler dessus

**Comment by alix-tz** [comment]
Je crois qu'il manque juste l'indication sur comment ajouter des badges dans le readme. Tu avais mentionné vouloir l'ajouter

**Comment by PonteIneptique** [comment]
> Tu avais mentionné vouloir l'ajouter
Ah oui :D Attends, je fais ça avant d'aller me coucher :D

**Comment by alix-tz** [comment]
Pour plus tard, quand tu auras été te coucher : je n'arrive pas à faire marcher l'option "automatically create a release", j'ai à chaque fois l'erreur suivante :  

https://github.com/HTR-United/lectaurep-repertoires/runs/5324260631?check_suite_focus=true

**Comment by PonteIneptique** [comment]
Je me demande si c'est parce que t'as une version 1.0.
Essaye de faire manuellement une version 1.0.0 avant ?

**Comment by alix-tz** [comment]
Effectivement, ça a résolu le problème

**Comment by PonteIneptique** [comment]
Faudrait peut-etre ajouter un avertissement la dessus (obligation du format X.X.X et pas de X.X)

**Comment by PonteIneptique** [comment]
Fixed !
