### ISSUE TITLE
Swap License and Format in the form

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#65]
Or put them on two separate lines, or default to an empty value instead of ALTO. Otherwise I think users might forget to modify this info.

~~Also, we should probably remove a couple of the examples in the "Language" field (or have a button to flush the field?)~~ -> cf. #66

**Comment by alix-tz** [comment]
If you chose to leave the Format field empty, for ex:

``` html
            <div class="col-sm-3">
              <select name="format" id="format" class="form-control">
                <option selected>---</option>
                <option value="Alto-XML">ALTO XML</option>
                <option value="Page-XML">PAGE XML</option>
                <!-- Ajouter d'autres options !-->
              </select>
            </div>
```

Then we need to make to make "---" invalid before generating the metadata

![image](https://user-images.githubusercontent.com/33317799/155012951-a28e3ca5-98b7-4cfe-8857-bcbbb189976f.png)

**Comment by PonteIneptique** [comment]
Hmm, I disagree with this one. I think we could make it clearer it's important (some visual clue ?) or can you try with `disabled` on the option and `required`on the select ?

**Comment by PonteIneptique** [comment]
If `disabled` + `required` works, I am fine with it ;)
