### ISSUE TITLE
Redesign Navbar

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#71]
Following our exchange: 

- [x] move data reuse charter in footer 
- [ ] and add links to it on different pages
- [x] change "Form" to anything more meaningfull
- [x] simplifier "Accueil" (pas besoin du triplement)
- [x] ajouter des icônes

Et avec #62 ajouter lien vers Actions

**Comment by PonteIneptique** [comment]
- `Record your data` / `Enregistrez vos données` ?
- `Browse` / `Naviguer` (?)
- `Github Automation` / `Automatisation github` ?
