### ISSUE TITLE
Fix "Script(s)" key in schema?

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/htr-united.github.io#72]
I was getting an error while running HTRUC :  

https://github.com/HTR-United/lectaurep-repertoires/runs/5324026301?check_suite_focus=true

```
Run htruc test htr-united.yml
1 to be tested
☒ File `htr-united.yml` testing failed
  'script' is a required property

0.00% of schema passed (0/1)
Error: Process completed with exit code 255.
```

The form created the "scripts" key today :  
![image](https://user-images.githubusercontent.com/33317799/155594107-ed961d5b-227e-4607-aeff-f61a8fdc6468.png)

I fixed the bug for my repo by manually changing "Scripts" into "Script". Is it a bug in the form or should we update the schema?

![image](https://user-images.githubusercontent.com/33317799/155594020-9bf44718-67bf-415e-ae79-e9a92deb0bbf.png)

**Comment by PonteIneptique** [comment]
Bug in the form, coming back with a commit.
